# -*- mode: python -*-

block_cipher = None

scipy_dlls = [('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libbanded5x.RKQBG52LDJE7SMU4UTFRPL23RQD5H6HV.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libbispeu.5N2XSD7URZS4WTOSLTOG4DDMA4HGB46U.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libblkdta00.IAFW7FLSVGSPL4J4YDEF3SZSULAQVAUB.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libchkder.6HLXPVTQJEGRZGLI5DFRMNW3SS76BHP6.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libcobyla2.JEGTSUUFJ7DFXWZN5PAYZTTLBDATC4WD.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdcosqb.K4J3XBR4PEETMRHZICUWW4LXG5UONZ34.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdcosqb.QRGA36MB6CFHWLQN6ETWARR4M4E6P3C2.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdcsrch.I2AOPDCXAPDRFNPWY55H5UE7XZSU5CVN.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdet.LNTYKFZX466ZGXSX5QG3Q7CT2EXBIBH7.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdfft_sub.WRRRTPQHZRNLI4VQIOVREMZ4WQUMLKKM.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdfitpack.6VKCDGWVRKJSDDBHY5M6TIU325Q2OYHW.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdgamln.XCREWSMFNS2HCSY3XUFZVHQW56G6QS2A.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdop853.6TJTQZW3I3Q3QIDQHEOBEZKJ3NYRXI4B.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libdqag.ANI7WYGVLGJCLVEMS6ZTJSRUFQDF26LA.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libd_odr.P3BR2UO4ANZCFXATXDRIT4QP4TFBFRQA.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\liblbfgsb.S2CGQXEV6CSOR3X2PM6EDQQZQIX46NKM.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libmvndst.KJP3NEE63DTR5HRJDNPRBMM4LKUW7NWF.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libnnls.5LTQOLAJY5PFO6MOEXWNMRWVFRWHYHKT.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libslsqp_op.NNY57ZXZ43A4RH3YWFA7BKHP5PC2K3I5.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libspecfun.PT6DS3HUOGYNSXUO4OUKK6ATA7B5KP2K.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libSTOPTEST.2FK2FXZ3RISMRIUPA3EBNTYOM45EPBAU.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libvode.UHFZSU643PZLGYRR6CJ6KD7PTCNAJ53P.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libwrap_dum.BGB3N2UT2RY5UW43XVRMCO5JAPG3ZMP4.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\libwrap_dum.HRA3RTF3AJ5XZFUUQRKFLF2KQDEJCCGJ.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\lib_arpack-.7JIJY32PHKUSLGUFPO7URFHCF7KZ472V.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\lib_blas_su.K3OEUGMAT2OUEYZDTK3SRQFJILATTZKM.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\lib_test_fo.JF5HTWMUPBXWGAYEBVEJU3OZAHTSVKCT.gfortran-win_amd64.dll', '.'),
              ('C:\\Users\\lifel\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\scipy\\extra-dll\\msvcp140.dll', '.')]

hidden_imports = ['textgenrnn',
                  'numpy',
                  'scipy',
                  'scipy._lib.messagestream',
                  'scipy.signal',
                  'scipy.signal.bsplines',
                  'scipy.special',
                  'scipy.special._ufuncs_cxx',
                  'scipy.linalg.cython_blas',
                  'scipy.linalg.cython_lapack',
                  'scipy.integrate',
                  'scipy.integrate.quadrature',
                  'scipy.integrate.odepack',
                  'scipy.integrate._odepack',
                  'scipy.integrate.quadpack',
                  'scipy.integrate._quadpack',
                  'scipy.integrate._ode',
                  'scipy.integrate.vode',
                  'scipy.integrate._dop',
                  'scipy._lib',
                  'scipy._build_utils',
                  'scipy.__config__',
                  'scipy.integrate.lsoda',
                  'scipy.cluster',
                  'scipy.constants',
                  'scipy.fftpack',
                  'scipy.interpolate',
                  'scipy.io',
                  'scipy.linalg',
                  'scipy.misc',
                  'scipy.ndimage',
                  'scipy.odr',
                  'scipy.optimize',
                  'scipy.setup',
                  'scipy.sparse',
                  'scipy.spatial',
                  'scipy.special',
                  'scipy.stats',
                  'scipy.version']

a = Analysis(['model.py'],
             pathex=['C:\\Users\\lifel\\Programming\\MA\\Class I\\chatbot\\email\\extension'],
             binaries=scipy_dlls,
             datas=[],
             hiddenimports=hidden_imports,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='model',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
